dbt_env_vars_template:
  outputs:
    dev:
      type: snowflake
      account: ""
      user: ""
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      threads: 8

    prod:
      type: snowflake
      account: ""
      user: ""
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      threads: 8

  target: dev
